export const courses = [
  {
    name: "B.A – English",
    slug: "ba-english",
    shortDescription:
      "Strengthens language, literature, and communication skills for media, education, and content careers.",
    duration: "3 Years",
    eligibility: "10+2 or equivalent",
    department: "B.A – English",
    seats: 40,
    affiliation: "University of Madras",
    fee: "₹20,000 / year",
    placementRate: "90%",
    avgPackage: "₹3.6 LPA",
    highlights: [
      "British and world literature",
      "Academic and creative writing",
      "Communication and language labs",
    ],
    careers: [
      "Content Writer",
      "Editor",
      "Teacher",
      "Communications Executive",
    ],
    topRecruiters: ["Sutherland", "Tech Mahindra", "HCL", "Infosys BPM"],
  },
  {
    name: "B.Sc – Psychology",
    slug: "bsc-psychology",
    shortDescription:
      "Builds foundations in cognitive, social, and clinical psychology with practical case-based learning.",
    duration: "3 Years",
    eligibility: "10+2 or equivalent",
    department: "B.Sc – Psychology",
    seats: 50,
    affiliation: "University of Madras",
    fee: "₹24,000 / year",
    placementRate: "91%",
    avgPackage: "₹3.8 LPA",
    highlights: [
      "Counselling and developmental psychology",
      "Research methods and behavioural science",
      "Internship exposure in wellness settings",
    ],
    careers: [
      "Counsellor Assistant",
      "Behavioural Analyst",
      "HR Associate",
      "Research Assistant",
    ],
    topRecruiters: ["Apollo", "Fortis", "Byju's", "Sutherland"],
  },
  {
    name: "BBA – Business Administration",
    slug: "bba-business-administration",
    shortDescription:
      "Develops business, leadership, and management skills through practical projects and case studies.",
    duration: "3 Years",
    eligibility: "10+2 or equivalent",
    department: "BBA – Business Administration",
    seats: 60,
    affiliation: "University of Madras",
    fee: "₹24,000 / year",
    placementRate: "93%",
    avgPackage: "₹4.1 LPA",
    highlights: [
      "Marketing, finance, and operations",
      "Leadership and communication training",
      "Internship and industry project",
    ],
    careers: [
      "Business Analyst",
      "Marketing Executive",
      "HR Associate",
      "Management Trainee",
    ],
    topRecruiters: ["Accenture", "Deloitte", "HDFC Bank", "Cognizant"],
  },
  {
    name: "B.Com – General",
    slug: "bcom-general",
    shortDescription:
      "Covers accounting, taxation, finance, and business law for strong commerce career pathways.",
    duration: "3 Years",
    eligibility: "10+2 or equivalent",
    department: "B.Com – General",
    seats: 80,
    affiliation: "University of Madras",
    fee: "₹22,000 / year",
    placementRate: "92%",
    avgPackage: "₹3.9 LPA",
    highlights: [
      "Core accounting and taxation",
      "Business law and economics",
      "Career-focused project work",
    ],
    careers: [
      "Accountant",
      "Tax Associate",
      "Banking Executive",
      "Finance Analyst",
    ],
    topRecruiters: ["HDFC Bank", "Axis Bank", "Deloitte", "ICICI"],
  },
  {
    name: "B.Com – Accounting & Finance",
    slug: "bcom-accounting-finance",
    shortDescription:
      "Specialized commerce program focused on advanced accounting, auditing, and financial management.",
    duration: "3 Years",
    eligibility: "10+2 or equivalent",
    department: "B.Com – Accounting & Finance",
    seats: 70,
    affiliation: "University of Madras",
    fee: "₹23,000 / year",
    placementRate: "94%",
    avgPackage: "₹4.2 LPA",
    highlights: [
      "Advanced accounting and auditing",
      "Corporate finance and analytics",
      "Industry-aligned finance projects",
    ],
    careers: [
      "Audit Associate",
      "Accounts Executive",
      "Financial Analyst",
      "Banking Operations Executive",
    ],
    topRecruiters: ["Deloitte", "EY", "KPMG", "TCS"],
  },
];
